development:
  facebook_app_id: 1069038906461481
  facebook_app_secret: 7eddc4cff94645438cef0da604d8c52f
  google_app_id: 551744300503-otfj9ags9o15nhgso1rjg3omtng4rsvv.apps.googleusercontent.com
  google_app_secret: QuA2nB49GTyWsyuBVRwZaUcu
  crm_api_url: http://icecondos-crm.dev
  crm_api_token: ZuB2nB24GTyWsyuPVRwMaZmi
  mapbox_token: pk.eyJ1IjoidHp1YnlhayIsImEiOiIxNmI5OTMzYzM0NTdhZjc3MDJiNGQ5YjI0NWQ2MTg0YSJ9.xA_OjQLoZREbHhOX-XW0jQ
  mapbox_map: tzubyak.m8nb9c8d
  walkscore_token: a7a1448f92dfeef1926e20d173da4326
  crm_call_token: MiB2nB24GTyWsyuPVRwMaZOk
  facebook_url: http://facebook.com
  twitter_url: http://twitter.com

staging:
  facebook_app_id: 1069038906461481
  facebook_app_secret: 7eddc4cff94645438cef0da604d8c52f
  google_app_id: 551744300503-ivgml300qa557ptghs7ddutk9h9q3h5u.apps.googleusercontent.com
  google_app_secret: 8lghZVyl99k2KInhzKkIW-wR
  crm_api_url: http://crm.myicecondos.com
  crm_api_token: ZuB2nB24GTyWsyuPVRwMaZmi
  mapbox_token: pk.eyJ1IjoidHp1YnlhayIsImEiOiIxNmI5OTMzYzM0NTdhZjc3MDJiNGQ5YjI0NWQ2MTg0YSJ9.xA_OjQLoZREbHhOX-XW0jQ
  mapbox_map: tzubyak.m8nb9c8d
  walkscore_token: a7a1448f92dfeef1926e20d173da4326
  crm_call_token: MiB2nB24GTyWsyuPVRwMaZOk
  facebook_url: http://facebook.com
  twitter_url: http://twitter.com

production:
  facebook_app_id: 996769883683642
  facebook_app_secret: 59c6656bb3342509e53f08285b7dc2ed
  google_app_id: 551744300503-ivgml300qa557ptghs7ddutk9h9q3h5u.apps.googleusercontent.com
  google_app_secret: 8lghZVyl99k2KInhzKkIW-wR
  crm_api_url: http://crm.icecondos.com
  crm_api_token: ZuB2nB24GTyWsyuPVRwMaZmi
  mapbox_token: pk.eyJ1IjoidHp1YnlhayIsImEiOiIxNmI5OTMzYzM0NTdhZjc3MDJiNGQ5YjI0NWQ2MTg0YSJ9.xA_OjQLoZREbHhOX-XW0jQ
  mapbox_map: tzubyak.m8nb9c8d
  walkscore_token: a7a1448f92dfeef1926e20d173da4326
  crm_call_token: MiB2nB24GTyWsyuPVRwMaZOk
  facebook_url: http://facebook.com
  twitter_url: http://twitter.com
