development:
  access_key_id: AKIAIC7OHVPYHAR37ZVA
  secret_access_key: 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

staging:
  access_key_id: AKIAIC7OHVPYHAR37ZVA
  secret_access_key: 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

production:
  access_key_id: AKIAIC7OHVPYHAR37ZVA
  secret_access_key: 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