development:
  access_key_id: AKIAJZYBQM3U6TJIVWVA
  secret_access_key: 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

staging:
  access_key_id: AKIAJZYBQM3U6TJIVWVA
  secret_access_key: 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

production:
  access_key_id: AKIAJZYBQM3U6TJIVWVA
  secret_access_key: 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